FROM node:20-alpine

WORKDIR /app

COPY package.json /app/package.json
COPY apps/web/package.json /app/apps/web/package.json
COPY packages/shared-types/package.json /app/packages/shared-types/package.json
RUN npm install

COPY . /app

WORKDIR /app/apps/web
CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0", "--port", "3000"]

